name: TopIS
version: 2.0
api: [3.0.0-ALPHA6]
author: kuraLLsz
#Edit Và Việt Hóa Bởi Ghast Noob
main: kuraLLsz\Main

commands:
  is:
    description: Xem Thông Tin Is
  topis:
    description: Xem Top Is