---
secret: NamMoADiDaPhat
autoUpdate: false
commandChecker: true
https: false
disableBuyCommand: false
buyCommand: buy
debug: false
commandThrottleCount: 150
disable-secret-command: false
directPay: false
packagePageSize: 5
invalidBuyCommand: Please enter the correct command parameters.
urlError: Failed to generate the shortened URL.
chatEnabled: Your chat is now enabled.
chatAlreadyEnabled: Your chat is already enabled.
commandsExecuted: Your purchased packages have been credited.
pleaseVisit: Please click the link below to continue
turnChatBackOn: Type /ec to turn your chat back on.
packageNotFound: Package not found.
noPackagesForSale: We currently do not have any packages for sale.
toPurchase: To purchase a package, please type
howToNavigate: Browse through our packages by using
packageId: ID
packageName: Name
packagePrice: Price
pageNotFound: Page not found.
categoryMenu: Category Menu
inventoryMenuPrefix: Buycraft
chooseACategory: Choose a category
category: Category
inventoryMenuNotReady: The inventory menu has not been loaded yet. Please wait.
nextPage: Next Page
previousPage: Previous Page
homePage: Back to categories
commandExecuteNotEnoughFreeInventory: '%d free inventory slot(s) are required.'
commandExecuteNotEnoughFreeInventory2: Please empty your inventory to receive these
  items.
...
